### ISSUE TITLE
Challenge description images broken

### ISSUE THREAD

**Issue by TheTrashFactory** [LCOGT/serol#1]
e.g. https://serol-beta.lco.global/challenge/3/start/

**Comment by zemogle** [comment]
They don't work because you've written them in Markdown ;-) I'll need to enable Markdown on their text area.

**Comment by zemogle** [comment]
Having done some experimenting, I think putting HTML in the challenge description is going to be the most flexible.

**Comment by zemogle** [comment]
Having that field as HTML seems to work nicely.
